<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>PHP 8 for PHP Developers</title>
  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="css/scrolling-nav.css" rel="stylesheet">
</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">Start Bootstrap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="/index.php">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="/refresh.php">Refresh</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <header class="bg-primary text-white" style="height: 50px;">
    <div class="container">
      <h1>PHP 8 for PHP Developers</h1>
      <?= ($message) ? $message : ''; ?>
    </div>
  </header>

 <?php if ($examples) : ?>
 <section id="about">
    <div class="container">
		<?php 
		while ($list->valid()) {
			echo '<div class="row">' . PHP_EOL;
			for ($x = 0; $x < COLS; $x++) {
				if ($list->valid()) {
					$name = basename($list->current());
					$list->next();
				} else {
					$name = '&nbsp;';
				}
				printf(FORMAT, $name, $name);
			}
			echo '</div>' . PHP_EOL;
		}
		?>
	  <p><?= $examples; ?></p>
    </div>
  </section>
  <?php endif; ?>

   <?= $output; ?>

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; <a href="https://php-cl.com/">php-cl.com</a> 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Plugin JavaScript -->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom JavaScript for this theme -->
  <script src="js/scrolling-nav.js"></script>

</body>

</html>
